version: '3'

services:
  mongo:
    image: mongo
    hostname: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: pyrat
    restart: always
    command: mongod --auth
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
  web:
    build: .
    command: bash -c "python3 -m uvicorn server.main:app --host 0.0.0.0 --port 8080 --reload"
    volumes:
      - .:/code
    ports:
      - 8080:8080
    links:
    - mongo


volumes:
  mongodbdata:
    driver: local