version: '3'

services:
  web:
    build: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

And this is t
    depends_on:
      - api
  certbot:
    image: certbot/certbot
  mongo:
    image: mongo
    hostname: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: pyrat
    restart: always
    command: mongod --auth
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
  api:
    build: DockerFile
    command: bash -c "python3 -m uvicorn server.main:app --host 0.0.0.0 --port 8080 --reload"
    volumes:
      - .:/code
    ports:
      - 8080:8080
    links:
    - mongo


volumes:
  mongodbdata:
    driver: local